"""Seed content used only to populate PlatformSetting / ConfigOption on first run."""

import json

# Survey frequency & choices — seeded into ConfigOption, not used at runtime directly.
SURVEY_FREQUENCY_SEED = [
    ("always", "دائما"),
    ("usually", "غالبا"),
    ("sometimes", "أحيانا"),
    ("rarely", "نادرا"),
]

SURVEY_WEEKLY_MEETINGS_SEED = [
    ("one", "لقاء واحد (اذكر السبب أدناه)"),
    ("two", "لقائين"),
    ("other", "أخرى"),
]

EDUCATION_STAGE_SEED = [
    ("primary", "الابتدائي"),
    ("middle", "الإعدادي"),
    ("secondary", "الثانوي"),
]

ARABIC_MONTHS_SEED = [
    ("1", "يناير"), ("2", "فبراير"), ("3", "مارس"), ("4", "أبريل"),
    ("5", "مايو"), ("6", "يونيو"), ("7", "يوليو"), ("8", "أغسطس"),
    ("9", "سبتمبر"), ("10", "أكتوبر"), ("11", "نوفمبر"), ("12", "ديسمبر"),
]

FAMILY_SURVEY_FIELDS_SEED = [
    {"fields": "family_name", "label": "الاسم الكريم", "section": "data"},
    {"fields": "stage_primary,stage_middle,stage_secondary", "label": "أولادك في المرحلة الدراسية", "section": "data"},
    {"fields": "has_regular_family_meeting", "label": "هل هناك برنامج مستمر للقاء الأسري في بيتك؟", "section": "meeting"},
    {"fields": "weekly_meetings_count", "label": "عدد اللقاءات الأسبوعية", "section": "meeting"},
    {"fields": "weekly_meetings_one_reason", "label": "سبب لقاء واحد", "section": "meeting"},
    {"fields": "weekly_meetings_other", "label": "أخرى", "section": "meeting"},
    {"fields": "family_meeting_notes", "label": "ملاحظات حول التفاعل والاستفادة", "section": "meeting"},
    {"fields": "received_curriculum_book", "label": "هل وصلك كتاب منهج التربية؟", "section": "curriculum"},
    {"fields": "read_curriculum_book", "label": "هل قرأته؟", "section": "curriculum"},
    {"fields": "studied_curriculum_at_home", "label": "هل تدارستم الكتاب في البيت؟", "section": "curriculum"},
    {"fields": "curriculum_notes", "label": "ملاحظاتك حول الاستفادة من المقرر", "section": "curriculum"},
    {"fields": "hadith_at_home", "label": "هل يتم أخذ مقرر الحديث للأولاد في المنزل؟", "section": "child_curricula"},
    {"fields": "fiqh_at_home", "label": "هل يتم أخذ مقرر الفقه للأولاد في المنزل؟", "section": "child_curricula"},
    {"fields": "curricula_obstacles", "label": "هل توجد عوائق أو عقبات؟", "section": "child_curricula"},
    {"fields": "listens_riyadh_saliheen", "label": "هل تستمع مع أولادك إلى رياض الصالحين بشكل مستمر؟", "section": "riyadh"},
    {"fields": "riyadh_progress", "label": "إلى أي تسجيل وصلت؟", "section": "riyadh"},
    {"fields": "received_approved_films", "label": "هل وصلتك النسخة الصحيحة للأفلام المسموحة؟", "section": "entertainment"},
    {"fields": "watches_approved_only", "label": "هل تلتزم بمشاهدة الأفلام المسموحة فقط؟", "section": "entertainment"},
    {"fields": "outdoor_entertainment", "label": "هل يوجد برنامج ترفيهي للأولاد خارج البيت؟", "section": "entertainment"},
]

FAMILY_FIELD_SECTION_DEFAULTS = {
    "family_name": "data",
    "stage_primary": "data",
    "stage_middle": "data",
    "stage_secondary": "data",
    "has_regular_family_meeting": "meeting",
    "weekly_meetings_count": "meeting",
    "weekly_meetings_one_reason": "meeting",
    "weekly_meetings_other": "meeting",
    "family_meeting_notes": "meeting",
    "received_curriculum_book": "curriculum",
    "read_curriculum_book": "curriculum",
    "studied_curriculum_at_home": "curriculum",
    "curriculum_notes": "curriculum",
    "hadith_at_home": "child_curricula",
    "fiqh_at_home": "child_curricula",
    "curricula_obstacles": "child_curricula",
    "listens_riyadh_saliheen": "riyadh",
    "riyadh_progress": "riyadh",
    "received_approved_films": "entertainment",
    "watches_approved_only": "entertainment",
    "outdoor_entertainment": "entertainment",
}

TEACHER_SURVEY_FIELDS_SEED = [
    {"fields": "attendance_punctuality", "label": "هل تلتزم بحضور المواعيد الأسبوعية في وقتها؟"},
    {"fields": "lesson_preparation", "label": "هل تقوم بتحضير المادة الدراسية بشكل جيد قبل اللقاء؟"},
    {"fields": "main_obstacles", "label": "ما هي أهم العقبات التي تحول دون تحقيق تلك الفائدة؟"},
    {"fields": "student_punctuality", "label": "ما هو تقييمك لحضور تلاميذك الدروس في الوقت المحدد؟"},
    {"fields": "student_preparation_percentage", "label": "ما هي نسبة تلاميذك الذين يقومون بتحضير الدرس؟"},
    {"fields": "student_comprehension", "label": "ما هو تقييمك لمدى استيعاب تلاميذك لمحتوى المادة؟"},
    {"fields": "student_notes", "label": "ملاحظات تجاه مجموعة أو شخصية من تلاميذك"},
    {"fields": "family_role_rating", "label": "كيف هو تقييمك لدور الأسرة في أداء تلاميذك؟"},
    {"fields": "family_role_message", "label": "ما هي رسالتك للآباء والأمهات؟"},
    {"fields": "session_suggestions", "label": "ما هي اقتراحاتك لتحسين هذه الجلسات الأسبوعية؟"},
]

PROGRAM_SURVEY_SECTIONS_SEED = [
    {
        "code": "individual",
        "title": "المجال الفردي",
        "subtitle": "من خلال مسؤولي المتابعة في الأحياء",
        "fields": [
            ["has_daily_individual_program", "هل لديك برنامج يومي فردي؟"],
            ["daily_includes_quran_dhikr", "تحديد حزب يومي من القرآن مع الذكر والاستغفار والدعاء والصلاة على النبي ﷺ"],
            ["program_regular_scheduled", "هل برنامجك منتظم ومجدول؟"],
            ["persistence_and_makeup", "هل الأصل فيه المداومة، وإذا فاتتك فقرة هل تقضيها على الكيفية المذكورة في تقرير اللجنة التربوية؟"],
        ],
    },
    {
        "code": "binary",
        "title": "المجال الثاني: الثنائيات",
        "subtitle": "من خلال مسؤولي المتابعة في الأحياء",
        "fields": [
            ["binary_meeting_biweekly", "هل ينعقد لقاء الثنائيات مرة كل أسبوعين؟"],
            ["binary_meeting_full_agenda", "هل بنود اللقاء تشمل الحديث حول التطبيق والتفاعل مع دروس اللقاءات الأسبوعية (قرآن، تربية إيمانية، تربية أسرية، وغيرها)، ومشاركة المشاعر والتعاون على تجاوز العوائق والتذكير بالله وباليوم الآخر؟"],
            ["binary_reform_quarterly", "هل تُعاد تشكيل الثنائيات كل ثلاثة أشهر، بحيث تُقام دورة الثنائيات أربع مرات خلال السنة؟"],
        ],
    },
    {
        "code": "during_meeting",
        "title": "المجال الثالث: أثناء اللقاء",
        "subtitle": "مسؤول المتابعة في الحي من خلال مسؤولي المجموعات — تحويل اللقاءات إلى لقاءات تربوية للتغيير",
        "fields": [
            ["go_during_punctual_attendance", "الحضور الدائم في الوقت المحدد لهذه اللقاءات"],
            ["go_during_good_preparation", "التحضير الجيد الذي لا يتم قراءة الموضوع مرة واحدة"],
            ["go_during_programs_on_time", "إيصال البرامج في وقتها المحدد دون تأخير"],
            ["go_during_summarize_points", "تلخيص النقاط العملية الأساسية التي يُراد تحويلها إلى تطبيق"],
            ["go_during_evaluate_meeting", "تقييم اللقاء بعد انتهائه للوقوف على نقاط القوة والقصور"],
            ["go_during_extended_monthly_meeting", "هل تم تطويل اللقاء الشهري من ظهر الجمعة حتى الساعة 9:30 مساءً يوم السبت؟"],
        ],
    },
    {
        "code": "outside_meeting",
        "title": "مسؤول المجموعة — خارج اللقاء",
        "subtitle": "مسؤول المتابعة في الحي من خلال مسؤولي المجموعات",
        "fields": [
            ["go_outside_educate_members", "هل يسهم في تثقيف وتربية أفراد مجموعته؟"],
            ["go_outside_close_living", "هل يعيش مع إخوانه معايشة قريبة؟"],
            ["go_outside_reminder_meetings", "هل يعقد لقاءات تذكيرية مع المقصرين؟"],
            ["go_outside_special_care_difficulties", "هل يعطي عناية خاصة للإخوة الذين لديهم صعوبات لغوية أو ثقافية؟"],
        ],
    },
    {
        "code": "oasis",
        "title": "دور مسؤولي الواحات ومسؤولي المجموعة",
        "subtitle": "مسؤول المتابعة في الحي من خلال مسؤولي الواحات",
        "fields": [
            ["oasis_weekly_meeting", "هل لهم لقاءٌ دوريٌّ مرّةً كلّ أسبوع؟"],
            ["oasis_assess_program_benefit", "هل يقيمون مدى استفادة الإخوة من البرامج التربوية المقدَّمة؟"],
        ],
    },
    {
        "code": "foundational",
        "title": "البرنامج الدراسي التأسيسي",
        "subtitle": "مسؤولي المتابعة في الحي من خلال إدارة الحي — للشباب والشابات الذين أنهوا السنة الأولى الجامعية ولم يلتحقوا بالبرنامج العام",
        "fields": [
            ["foundational_monthly_faith_meeting_week4", "هل تم عقد لقاء إيماني شهري موسع في الأسبوع الرابع؟"],
        ],
    },
    {
        "code": "uncles",
        "title": "جلسات الأعمام",
        "subtitle": None,
        "fields": [
            ["uncle_platforms_created", "هل تم إنشاء منصات دورية للأعمام؟"],
        ],
    },
    {
        "code": "latecomers",
        "title": "التعامل مع المتأخرين عن الجلسات التربوية",
        "subtitle": "الالتزام التام بالمواعيد والجلسات — موعد الجلسة 7:30 مساءً، من لم يحضر عند 7:45 يُمنع من الدخول، من تغيب ثلاث جلسات متتالية يلتقي بإدارة الحي",
        "fields": [
            ["latecomers_commitment_enforced", "هل يُطبَّق الالتزام التام بالمواعيد والجلسات؟"],
            ["latecomers_session_starts_730", "هل موعد الجلسة تمام الساعة 7:30 مساءً؟"],
            ["latecomers_entry_bar_after_745", "هل يُمنع دخول من لم يكن حاضراً عند الساعة 7:45؟"],
            ["latecomers_three_absences_rule", "هل يُطبَّق منع حضور من تغيب ثلاث جلسات متتالية حتى يلتقي بإدارة الحي؟"],
        ],
    },
]

NAV_LABELS_SEED = {
    "dashboard": "لوحة التحكم",
    "super_admin": "المشرف الأعلى",
    "schools": "المدارس",
    "students": "الطلاب",
    "teachers": "المعلمون",
    "attendance": "الحضور",
    "evaluations": "المحاسبة",
    "self_assess": "محاسبتي",
    "questionnaires": "الاستبيانات",
    "followup_surveys": "المتابعة الشهرية",
    "exams": "الاختبارات",
    "kpi": "مؤشرات الأداء",
    "more": "المزيد",
    "reading": "القراءة",
    "behavior": "السلوك",
    "ai_assistant": "المساعد الذكي",
    "reports": "التقارير",
    "admin": "إعدادات النظام",
    "users": "المستخدمون",
    "notifications": "الإشعارات",
    "logout": "تسجيل الخروج",
    "profile": "الملف الشخصي",
    "my_account": "حسابي",
    "account_view": "عرض الحساب",
    "as_teacher": "كمعلم",
    "as_student": "كطالب",
    "menu": "القائمة",
    "license_request": "طلب ترخيص",
    "tenants": "المستأجرون",
}

REGISTRATION_SECTION_LABELS_SEED = {
    "personal": "المعلومات الشخصية",
    "location": "الموقع",
    "account": "حساب الدخول",
    "academic": "التصنيف الدراسي",
}

PAGE_LABELS_SEED = {
    "reports_hub_title": "مركز التقارير",
    "reports_hub_subtitle": "تصدير وتنزيل جميع التقارير — أكاديمية ومتابعة شهرية",
    "reports_family_complete": "أسرة مكتملة",
    "reports_family_partial": "أسرة جزئية/فارغة",
    "reports_teacher_complete": "معلم مكتمل",
    "reports_program_complete": "برنامج مكتمل",
    "reports_tab_students": "تقارير الطلاب",
    "reports_tab_teachers": "تقارير المعلمين",
    "dashboard_teacher": "لوحة تحكم المعلم",
    "dashboard_student": "لوحة الطالب",
    "dashboard_school": "لوحة المدرسة",
    "dashboard_parent": "لوحة ولي الأمر",
    "teacher_survey_title": "استبيان شهري للمعلم حول لقاءات التلاميذ",
    "teacher_survey_subtitle": "مسؤولي المتابعة في الحي — من خلال إدارة الحي",
    "family_form_header": "الأسرة — مسؤول المتابعة في الحي من خلال مسؤولي المجموعات",
    "family_form_subtitle_prefix": "استبيان متابعة الأسرة",
    "family_form_notice": "هذه الصفحة = استبيان الأسرة فقط ({n} سؤال).",
    "family_form_teacher_link": "تبويب استبيان المعلم",
    "family_section_data": "بيانات الأسرة",
    "family_section_meeting": "اللقاء الأسري",
    "family_section_curriculum": "منهج التربية",
    "family_section_child_curricula": "مقررات الأبناء",
    "family_section_riyadh": "برنامج رياض الصالحين",
    "family_section_entertainment": "الترفيه والمشاهدة",
    "family_stages_label": "أولادك في المرحلة الدراسية:",
    "family_parent_label": "ولي الأمر (اختياري)",
    "family_name_label": "الاسم الكريم",
    "survey_save": "حفظ الاستبيان",
    "survey_cancel": "إلغاء",
    "family_checklist_title": "قائمة أسئلة استبيان الأسرة",
    "teacher_checklist_title": "قائمة أسئلة استبيان المعلم",
    "dashboard_student_greeting": "مرحباً",
    "dashboard_welcome": "مرحباً بك في {platform}",
    "kpi_page_title": "مؤشرات الأداء",
    "student_stat_overall_kpi": "مؤشر الأداء الكلي",
    "student_stat_attendance": "نسبة الحضور",
    "student_stat_gpa": "المعدل التراكمي",
    "student_stat_class": "الفصل",
    "student_kpi_dynamic_header": "مؤشرات الأداء الديناميكية",
    "student_actions_header": "إجراءات",
    "student_action_self_assess": "المحاسبة الذاتية",
    "student_action_profile": "ملفي الشخصي",
    "student_action_kpi": "مؤشرات الأداء",
    "student_action_exams": "الاختبارات",
    "student_action_followup": "متابعة شهرية",
    "student_action_edit": "تعديل بياناتي",
    "teacher_stat_students": "طالب تحت متابعتي",
    "teacher_stat_surveys_complete": "استبيانات مكتملة",
    "teacher_stat_surveys_remaining": "استبيانات متبقية",
    "teacher_stat_completion": "إنجاز متابعة {month}/{year}",
    "teacher_alert_followup_required": "متابعة شهرية مطلوبة",
    "teacher_alert_followup_body": "يجب تقييم كل طالب عبر استبيانات المتابعة الشهرية ({month}/{year}).",
    "teacher_alert_teacher_survey": "استبيان المعلم: {answered}/{total}",
    "teacher_alert_pending": "{n} طالب لم يُقيَّم",
    "teacher_alert_partial": "{n} جزئي",
    "teacher_btn_complete_surveys": "إكمال التقييمات",
    "teacher_alert_all_done": "أتممت متابعة جميع طلابك واستبيان المعلم لشهر {month}/{year}.",
    "teacher_students_card_title": "أداء طلابي ومتابعتهم الشهرية",
    "teacher_btn_analytics": "تحليلات",
    "teacher_btn_followup_surveys": "استبيانات المتابعة",
    "teacher_col_student": "الطالب",
    "teacher_col_group": "المجموعة",
    "teacher_col_kpi": "مؤشر الأداء",
    "teacher_col_survey": "استبيان المتابعة",
    "teacher_col_questions": "{answered}/{total} سؤال",
    "teacher_btn_profile": "الملف",
    "teacher_btn_rate": "تقييم",
    "teacher_btn_view": "عرض",
    "teacher_no_students": "لا يوجد طلاب مرتبطون بمجموعاتك. تأكد من تعيينك كمسؤول أو معلم للفصل.",
    "teacher_classes_header": "فصولي الدراسية",
    "teacher_btn_attendance": "تسجيل الحضور",
    "teacher_btn_evaluations": "المحاسبة",
    "teacher_no_classes": "لا توجد فصول مخصصة.",
    "teacher_quick_actions": "إجراءات سريعة",
    "teacher_quick_followup": "استبيانات المتابعة الشهرية",
    "teacher_quick_students": "الطلاب",
    "teacher_quick_daily_eval": "المحاسبة اليومية",
    "teacher_quick_attendance": "الحضور",
    "teacher_quick_analytics": "تحليلات المتابعة",
    "hub_title": "المتابعة الشهرية — {month}/{year}",
    "hub_includes": "يشمل استبيان المعلم ({teacher_n} أسئلة) + استبيان الأسرة ({family_n} سؤال لكل طالب) + البرنامج التربوي ({program_n} سؤال لكل طالب) — كالنماذج المطبوعة",
    "hub_eval_required": "تقييم مطلوب لكل طالب",
    "hub_family_pending": "{n} أسرة لم تبدأ",
    "hub_family_partial": "{n} أسرة جزئي",
    "hub_program_pending": "{n} برنامج لم يبدأ",
    "hub_program_partial": "{n} برنامج جزئي",
    "hub_teacher_survey_progress": "استبيان المعلم: {answered}/{total}",
    "hub_btn_family": "إكمال استبيانات الأسرة",
    "hub_btn_program": "إكمال البرنامج التربوي",
    "hub_all_done": "أتممت استبيان المعلم واستبيانات الأسرة والبرنامج التربوي لجميع طلابك لهذا الشهر.",
    "hub_tab_teacher": "استبيان المعلم ({n})",
    "hub_tab_family": "استبيان الأسرة ({n} × {students} طالب)",
    "hub_tab_program": "البرنامج التربوي ({n} × {students} طالب)",
    "hub_tab_teacher_hint": "تبويب ١: استبيان المعلم ({n} أسئلة) — كالنموذج المطبوع «مسؤولي المتابعة — إدارة الحي».",
    "hub_tab_family_hint": "تبويب ٢: استبيان الأسرة ({n} سؤال لكل طالب) — «مسؤول المتابعة من خلال مسؤولي المجموعات».",
    "hub_family_section_alert": "الأسرة — مسؤول المتابعة في الحي من خلال مسؤولي المجموعات — {n} سؤالاً لكل أسرة/طالب",
    "hub_program_section_alert": "البرنامج التربوي — متابعة شهرية لكل طالب — {n} سؤالاً لكل طالب",
    "hub_save_family": "حفظ استبيان هذه الأسرة",
    "hub_save_program": "حفظ البرنامج التربوي لهذا الطالب",
    "hub_save_teacher": "حفظ استبيان المعلم",
    "hub_back": "← رجوع للقائمة",
    "hub_no_students": "لا يوجد طلاب مرتبطون بهذا المعلم/المجموعة.",
}


def dumps_json(data):
    return json.dumps(data, ensure_ascii=False)
